services:

  mindcode-db:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_DB: mindcode_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
    volumes:
      - mindcode-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mindcode-web:
    build:
      context: .

    depends_on:
      - mindcode-db
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  mindcode-postgres-data:
    driver: local
