services:
  mindcode-db:
    image: postgres:17
    restart: on-failure
    environment:
      POSTGRES_DB: mindcode_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_password
    volumes:
      - mindcode-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mindcode-net

  mindcode-web:
    build:
      context: .

    depends_on:
      - mindcode-db
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - mindcode-net

volumes:
  mindcode-postgres-data:
    driver: local

networks:
  mindcode-net:
    driver: bridge
